// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickHomeExpenseSummarizer.Entity;

#nullable disable

namespace QuickHomeExpenseSummarizer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250328195105_Add_FilterCategory_and_CategoryItem")]
    partial class Add_FilterCategory_and_CategoryItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("QuickHomeExpenseSummarizer.Entity.CategoryItem", b =>
                {
                    b.Property<int>("CategoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilterCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryItemId");

                    b.HasIndex("FilterCategoryId");

                    b.ToTable("CategoryItem");
                });

            modelBuilder.Entity("QuickHomeExpenseSummarizer.Entity.FilterCategory", b =>
                {
                    b.Property<int>("FilterCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FilterCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("QuickHomeExpenseSummarizer.Entity.SourceFolder", b =>
                {
                    b.Property<int>("SourceFolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SourceFolderId");

                    b.ToTable("SourceFolders");
                });

            modelBuilder.Entity("QuickHomeExpenseSummarizer.Entity.CategoryItem", b =>
                {
                    b.HasOne("QuickHomeExpenseSummarizer.Entity.FilterCategory", "FilterCategory")
                        .WithMany("Items")
                        .HasForeignKey("FilterCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterCategory");
                });

            modelBuilder.Entity("QuickHomeExpenseSummarizer.Entity.FilterCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
